# Tools

## IDE

Now that you know the basics of Web Development you are ready to go and write some code!

But there is still a question left to answer.

Where do programmers write their code. Surely not in a Word document or the default text editor of their operating system. Developers use an Integrated Development Environment (IDE) to write code because it comes with a lot of handy features that help developers code faster and cleaner.

The most IDEs have a lot of features that you probably wont even need during this course but once you get used to the following advantages you don't want to code without them anymore.

**1. Graphical User Interface**  
The GUI of an IDE has been designed in a way that allows you to see your file directory, editor, terminal and some IDEs even have an interface to download packages and even for version control.

**2. Autocomplete**  
If the IDE knows your programming language it can anticipate what you are going to type next and it will pop up some autocompletion suggestions.

**3. Syntax Highlighting**  
The IDE can also provide some visual aid to your syntax based on your programming language, so that special words have a different color, opening and closing parentheses will have the same color. This may seem distracting at the beginning but once you get used to it, it will help you code faster.

**4. Debugging**  
No one can avoid to write code without bugs. IDEs know that and they are always in search of your mistakes such as typos, syntax errors and even reference errors. The cool thing is that it will show you the error even before you run your code. That way you don't have to wait for your code to run and break.

Some popular IDEs for Web Development are Visual Studio Code, Vim and Sublime Text 3. We recommend you to use [Visual Studio Code](https://code.visualstudio.com/) as it is also used in the Udemy Course you will be learning with.

For this course and your project you can also use the online code editor [CodeSandbox](https://codesandbox.io/). This IDE is based on the same platform as Visual Studio Code, but offers some additional functionalities. You can create teams that can not only access the same files but you can also have a live coding session together in the same file. To sign up you need a free account, which you can create in a matter of seconds.

## API

This semester the web development course will build an interactive weather application but more on the project will come later. For now let's answer the question: Where does our weather data come from? Obviously we do not keep track of the weather data. There are plenty of APIs that provide such a service. But what exactly is an API? An API (Application Programming Interface) allows programmers to get some data from somewhere else and do whatever you want to do with it. For example you could display such data on your web page. These API services are often expensive but there are some very cool APIs that allow us to do some stuff for free.

### How do we get the data?
Every API works differently but if you understand one API you probably will also understand every other API very easily. We have to write some code that asks the API what data we want? In JavaScript you can use the fetch() function to request data from somewhere.

### How do we use the data?
After you fetched the data from an API you have to change the format of the data into an JavaScript object so that you can work with those information. Some of you might ask in which form the data comes to us and that would be very good question. Most API Services use JSON (JavaScript Object Notation) to send data. You can read more about it in the additional resources part but for now you should know that it is a text-based format for representing structured data based on JavaScript object syntax. It is commonly used for transmitting data in web applications (e.g., sending some data from the server to the client). 

For your project we recommend you to use the [OpenWeather API](https://openweathermap.org/api) which has a free tier that you can use after creating a free account. If you read their documentation page you will see many different API options you can choose from. But don't worry! Once you know how one of them works you will get the hang of it. You can start with the „Current Weather Data API Call“ and inspect the data structure. Note which data you will need and try to extract it from there. You can use a Chrome Extension called JSON Formatter to have a clear look at the data.

## Udemy
