--- 
title: "Weather App Project SoSe22"
author: "TechAcademy e.V."
date: "Summer Term 2022"
site: bookdown::bookdown_site
---

# Introduction
Welcome to the web-development program for the summer term of 2022!
You've just gotten accepted into our web-development program for the summer term of 2022 and want to know what's it all about actually? Maybe you signed up, because of our awesome marketing's team TikTok campaign, or you may already have an app idea in your head. Whatever the reason may be, we can assure you of one thing: If you follow through with the semester, you will have gained an awesome skill to have and a solid foundation for further programming adventures. We will help and guide you along the way to the best of our abilities and hope we can share some of that fascination that got us into programming with you!  

Learning to code is incredibly rewarding but can also be difficult and frustrating. Like any skill worth knowing, it takes time to acquire, and it can’t be learned in a weekend or even a month. With that said, anyone can learn how to program as long as they are willing to put in the time and effort.

So before we get into the meat and get our hands dirty, let's go over how this semester is structured. Over the following months, there will be a total of four Coding Meetups, spaced out evenly where you will have the ability to meet your peers, work together on our application and ask questions to your mentors. But what about the rest of the semester? As mentioned previously any skill takes time. So you will have to do work on your own as well. For self-study purposes this guideline only serves as a rough draft. However, we have partnered up with Udemy and thus you have free access to the ultimate web-development bootcamp course. Everything you will learn there, you can later use within your own project and solidify your knowledge. 

In your project, you can work in groups of up to four team members. You can choose your teammates independently and we will not interfere with your arrangements. It is however beneficial, that all group members have approximately the same level of knowledge. We explicitly encourage you to collaborate with students from different university faculties. This not only allows you to get to know people from other faculties, but may also give you a whole new perspective on the project and tasks. When submitting your project please note: for a certificate, each person must submit the project individually. However, hand-ins may be similar within your group. You can get more information at our first Coding Meetup on **May 18, 2022.**

Every semester, the Product Development Team at TechAcademy thinks hard about a new project that is suited for you to get into web-development.
This semester we decided to let you create a weather-app. You've seen them countless times on various websites and may use your favourite one every day to check if you have to put on a raincoat or sunscreen. But how does the data get to the website? How does it update with every refresh and how can one make look that all appealing to an audience? These are all questions that we will tackle in this semester. We hope you are as hyped up about that as we are!  

The model weather-app that you will see later on in the course and this associated project guide was developed and written entirely from scratch by [Sebastian Hönig](https://www.linkedin.com/in/sebastian-hönig/) and [Burak Onat](https://www.linkedin.com/in/tburakonat/) from TechAcademy’s Web Development Team.


